# -*- coding: utf-8 -*-
"""Fibonacci.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QTi_MVvYkTDF6qUL_WjhS-9Cb2QrOkX1
"""

import streamlit as st

st.title("Sequência de Fibonacci")

# Solicita o número de repetições ao usuário
num_repetitions = st.number_input(
    "Quantas repetições da sequência de Fibonacci você deseja?",
    min_value=1,
    max_value=1000,
    value=10,
    step=1,
)

# Gera a sequência ao clicar no botão
if st.button("Gerar sequência"):
    # Inicializa os dois primeiros números da sequência
    a, b = 0, 1

    # Lista para armazenar a sequência de Fibonacci
    fibonacci_sequence = []

    # Gera a sequência de Fibonacci
    for _ in range(int(num_repetitions)):
        fibonacci_sequence.append(a)
        a, b = b, a + b

    # Exibe a sequência gerada
    st.subheader("Sequência de Fibonacci:")
    st.write(fibonacci_sequence)